views.style.flexible_table:
  type: views_style
  label: 'Flexible Table'
  mapping:
    columns:
      type: sequence
      label: 'Columns'
      sequence:
        type: string
        label: 'Columns name'
    default:
      type: string
      label: 'Default sort'
    info:
      type: sequence
      label: 'Columns info'
      sequence:
        type: mapping
        label:  'Column info'
        mapping:
          default_visible:
            type: boolean
            label: 'Column visible on default'
          sortable:
            type: boolean
            label: 'Sortable'
          default_sort_order:
            type: string
            label: 'Default order'
          align:
            type: string
            label: 'Align'
          separator:
            type: string
            label: 'Separator'
          empty_column:
            type: boolean
            label: 'Hide empty columns'
          responsive:
            type: string
            label: 'Responsive'
    override:
      type: boolean
      label: 'Override normal sorting if click sorting is used'
    sticky:
      type: boolean
      label: 'Enable Drupal style "sticky" table headers (Javascript)'
    summary:
      type: label
      label: 'Summary title'
    order:
      type: string
      label: 'Default order'
    empty_table:
      type: boolean
      label: 'Show the empty text in the table'
    caption:
      type: label
      label: 'Caption for the table'
    description:
      type: text
      label: 'Table description'
